name: BugReport
version: 0.12.5
main: com.leon.bugreport.BugReportPlugin
api-version: 1.13
author: ItsLeon15
softdepend: [ PlaceholderAPI, Plan ]

permissions:
  bugreport.admin:
    description: Allows the player to manage bug reports
    default: op
  bugreport.notify:
    description: Receive notifications for bug reports
    default: op
  bugreport.archived:
    description: Allows the player to access the archived bug reports
    default: op
  bugreport.settings:
    description: Allows the player to access and change the settings of the plugin
    default: op
  bugreport.list:
    description: Allows the player to access the list of bug reports
    default: op
  bugreport.use:
    description: Allows the player to use the bug report command
    default: op
  bugreport.archive:
    description: Allows the player to archive bug reports
    default: op
  bugreport.delete:
    description: Allows the player to delete bug reports
    default: op

commands:
  bugreport:
    aliases:
      - br
    description: Submit a bug report
    usage: /bugreport <message>
    executor: com.leon.bugreport.BugReportCommand
  buglist:
    aliases:
      - bl
    description: View bug reports
    usage: /buglist
    executor: com.leon.bugreport.commands.BugListCommand
  buglinkdiscord:
    aliases:
      - bld
    description: Link a Discord webhook to the server
    usage: /buglinkdiscord <Webhook URL>
    executor: com.leon.bugreport.LinkDiscordCommand
  buglistarchived:
    aliases:
      - bla
    description: Lists all archived bug reports
    usage: /buglistarchived
    executor: com.leon.bugreport.BugListArchivedCommand
  buglistsettings:
    aliases:
      - bls
    description: View the plugin settings
    usage: /buglistsettings
    executor: com.leon.bugreport.BugListSettingsCommand
